federation_version: =2.3.5
subgraphs:
  shows:
    routing_url: http://host.docker.internal:8080/graphql
    schema:
      file: ./../../shows-dgs/src/main/resources/schema/schema.graphqls
  reviews:
    routing_url: http://host.docker.internal:8081/graphql
    schema:
      file: ./../../reviews-dgs/src/main/resources/schema/schema.graphqls
  authors:
    routing_url: http://host.docker.internal:8082/graphql
    schema:
      file: ./../../authors/src/main/resources/graphql/schema.graphqls