federation_version: =2.3.5
subgraphs:
  shows:
    routing_url: http://host.docker.internal:8080/graphql
    schema:
      file: ./subgraph/shows.schema.graphqls
  reviews:
    routing_url: http://host.docker.internal:8081/graphql
    schema:
      file: ./subgraph/reviews.schema.graphqls
  authors:
    routing_url: http://host.docker.internal:8082/graphql
    schema:
      file: ./subgraph/authors.schema.graphqls